# A CI configuration to auto-publish pub packages.

name: Publish

on:
  pull_request:
    branches: [ master ]
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+*' ]

jobs:
  publish:
    # These permissions are required for authentication using OIDC and to enable
    # us to create comments on PRs.
    permissions:
      id-token: write
      pull-requests: write
    if: ${{ github.repository_owner == 'dart-lang' }}
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
